apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scraper-service
  template:
    metadata:
      labels:
        app: scraper-service
    spec:
      containers:
        - name: scraper-service
          image: scraper_service:latest
          ports:
            - containerPort: 8787
            - containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  selector:
    app: scraper-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8787
    - protocol: TCP
      port: 9095
      targetPort: 9095
